fix: pytest --help (#104)
help should be a `str` not a `tuple` otherwise it breaks `pytest --help`

Before the fix `pytest --help` is exiting with the following error
```
    if action.help and action.help.strip():
                       ^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'strip'
```

After the fix `pytest --help` is working as usual